const JAPAN_VIEW={center:[36.5,137],zoom:5};
const BOUNDS=L.latLngBounds([20,120],[50,155]);
const TILE={blank:{label:'白地図',url:'https://cyberjapandata.gsi.go.jp/xyz/blank/{z}/{x}/{y}.png',minZoom:5,maxZoom:14},pale:{label:'淡色地図',url:'https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',minZoom:2,maxZoom:18},std:{label:'標準地図',url:'https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png',minZoom:2,maxZoom:18}};
const ATTR='<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">地理院タイル</a>';
const map=L.map('map',{center:JAPAN_VIEW.center,zoom:JAPAN_VIEW.zoom,minZoom:4,maxZoom:14,maxBounds:BOUNDS,maxBoundsViscosity:.82,zoomControl:true,attributionControl:true});
const layers={};let activeBase='blank',prefLayer=null,labelLayer=null,terrainLayer=null,showTooltip=true;
Object.entries(TILE).forEach(([id,cfg])=>{layers[id]=L.tileLayer(cfg.url,{minZoom:cfg.minZoom,maxZoom:cfg.maxZoom,maxNativeZoom:cfg.maxZoom,attribution:ATTR,crossOrigin:true,updateWhenIdle:false,keepBuffer:3})});
layers.blank.addTo(map);
terrainLayer=L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/hillshademap/{z}/{x}/{y}.png',{minZoom:2,maxZoom:16,maxNativeZoom:16,opacity:.3,attribution:ATTR,crossOrigin:true});
terrainLayer.addTo(map);
L.Control.Reset=L.Control.extend({options:{position:'topleft'},onAdd(){const a=L.DomUtil.create('a','leaflet-control-reset');a.href='#';a.title='全国へ戻る';a.textContent='全';L.DomEvent.disableClickPropagation(a);L.DomEvent.on(a,'click',event=>{L.DomEvent.preventDefault(event);map.setView(JAPAN_VIEW.center,JAPAN_VIEW.zoom)});return a}});
new L.Control.Reset().addTo(map);
function setStatus(text){document.getElementById('mapStatus').textContent=text}
function setBase(id){if(!TILE[id])return;Object.values(layers).forEach(layer=>map.removeLayer(layer));layers[id].addTo(map);activeBase=id;document.querySelectorAll('[data-base]').forEach(button=>button.classList.toggle('active',button.dataset.base===id));setStatus(`${TILE[id].label}を表示中`)}
map.on('zoomend',()=>{if(activeBase==='blank'&&map.getZoom()>14)setBase('pale')});
fetch('./data/static/prefectures.geojson').then(response=>{if(!response.ok)throw new Error(`境界データ ${response.status}`);return response.json()}).then(data=>{prefLayer=L.geoJSON(data,{style:{color:'#526b66',weight:1,opacity:.88,fill:false},interactive:false,className:'pref-boundary'}).addTo(map)}).catch(error=>setStatus(`都道府県境界を読み込めません: ${error.message}`));
fetch('./data/static/place_labels.json').then(response=>response.json()).then(data=>{labelLayer=L.geoJSON(data,{filter:feature=>map.getZoom()>=(feature.properties.min_zoom||6),pointToLayer:(feature,latlng)=>L.marker(latlng,{interactive:false,icon:L.divIcon({className:`place-label ${feature.properties.kind}`,html:feature.properties.label,iconSize:null})})});if(document.getElementById('labelsToggle').checked)labelLayer.addTo(map)}).catch(error=>setStatus(`地名を読み込めません: ${error.message}`));
document.querySelectorAll('[data-base]').forEach(button=>button.addEventListener('click',()=>setBase(button.dataset.base)));
document.getElementById('prefToggle').addEventListener('change',event=>{if(!prefLayer)return;if(event.target.checked)prefLayer.addTo(map);else map.removeLayer(prefLayer)});
document.getElementById('labelsToggle').addEventListener('change',event=>{if(!labelLayer)return;if(event.target.checked)labelLayer.addTo(map);else map.removeLayer(labelLayer)});
document.getElementById('terrainToggle').addEventListener('change',event=>{if(event.target.checked)terrainLayer.addTo(map);else map.removeLayer(terrainLayer)});
document.getElementById('terrainOpacity').addEventListener('input',event=>terrainLayer.setOpacity(Number(event.target.value)/100));
document.getElementById('tooltipToggle').addEventListener('change',event=>{showTooltip=event.target.checked;if(!showTooltip)document.getElementById('tooltip').hidden=true});
let radarLayer=null,rasrfLayer=null;
async function latestJmaTile(kind){const isNow=kind==='nowc',target=isNow?'https://www.jma.go.jp/bosai/jmatile/data/nowc/targetTimes_N1.json':'https://www.jma.go.jp/bosai/jmatile/data/rasrf/targetTimes.json',rows=await fetch(target).then(r=>{if(!r.ok)throw new Error(`${kind} ${r.status}`);return r.json()}),row=rows[0],base=row.basetime,valid=row.validtime,member=row.member||'none',element=isNow?'hrpns':'rasrf',url=`https://www.jma.go.jp/bosai/jmatile/data/${kind}/${base}/${member}/${valid}/surf/${element}/{z}/{x}/{y}.png`;return L.tileLayer(url,{opacity:Number(document.getElementById('radarOpacity').value)/100,minZoom:2,maxZoom:10,maxNativeZoom:10,crossOrigin:true,attribution:'<a href="https://www.jma.go.jp/" target="_blank">気象庁</a>'})}
async function toggleWeather(kind,enabled){const key=kind==='nowc'?'radarLayer':'rasrfLayer';try{if(enabled){if(!globalThis[key])globalThis[key]=await latestJmaTile(kind);globalThis[key].addTo(map)}else if(globalThis[key])map.removeLayer(globalThis[key]);setStatus(enabled?`${kind==='nowc'?'レーダー雨量・雨雲の動き':'降水短時間予報'}を表示中`:`${TILE[activeBase].label}を表示中`)}catch(error){setStatus(`気象レイヤーを読み込めません: ${error.message}`);document.getElementById(kind==='nowc'?'radarToggle':'rasrfToggle').checked=false}}
document.getElementById('radarToggle').addEventListener('change',event=>toggleWeather('nowc',event.target.checked));
if(document.getElementById('rasrfToggle'))document.getElementById('rasrfToggle').addEventListener('change',event=>toggleWeather('rasrf',event.target.checked));
document.getElementById('radarOpacity').addEventListener('input',event=>{[globalThis.radarLayer,globalThis.rasrfLayer].filter(Boolean).forEach(layer=>layer.setOpacity(Number(event.target.value)/100))});
const views={map:'mapView',detail:'mapView',calendar:'mapView',mydata:'mapView'};
function setTab(tab){document.getElementById('mapView').classList.add('active');if(['detail','calendar'].includes(tab)&&analysis.selectedGrid!==null)openDetailModal();setTimeout(()=>map.invalidateSize(),0)}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
window.addEventListener('resize',()=>map.invalidateSize());

const analysis={manifest:null,points:null,values:null,mode:'pot_outdoor',kind:'moisture',slot:0,opacity:.5,canvas:null,ctx:null,selectedGrid:null,prefNames:null,hourly:{},daily:null};
const amedasRain={enabled:false,kind:'',values:null,canvas:null,ctx:null};
function moistureColor(v){const stops=[[0,[181,101,29]],[25,[232,197,71]],[50,[168,208,141]],[75,[74,144,217]],[100,[31,95,168]]];for(let i=1;i<stops.length;i++){if(v<=stops[i][0]){const a=stops[i-1],b=stops[i],t=(v-a[0])/(b[0]-a[0]);return `rgb(${a[1].map((x,j)=>Math.round(x+(b[1][j]-x)*t)).join(',')})`}}return 'rgb(31,95,168)'}
const LABEL_COLORS=['#d95f02','#5e9f68','#2d87c8','#8d6e63','#8e77ad','#a23b3b'];
const MEDAKA_COLORS=['#74add1','#f2c84b','#ed7d31','#c62828'];
function analysisColor(v){return analysis.kind==='moisture'?moistureColor(v):analysis.kind==='watering'?(LABEL_COLORS[v]||'#777'):analysis.kind==='rootrot'?(['#5e9f68','#d1b36f','#8e77ad','#a23b3b'][v]||'#777'):(MEDAKA_COLORS[v]||'#777')}
function ensureCanvas(){if(analysis.canvas)return;analysis.canvas=document.createElement('canvas');analysis.canvas.className='analysis-canvas';document.getElementById('map').appendChild(analysis.canvas);analysis.ctx=analysis.canvas.getContext('2d')}
function drawAmedasRain(){if(!amedasRain.enabled||!amedasRain.values||!analysis.points)return;if(!amedasRain.canvas){amedasRain.canvas=document.createElement('canvas');amedasRain.canvas.className='amedas-rain-canvas';document.getElementById('map').appendChild(amedasRain.canvas);amedasRain.ctx=amedasRain.canvas.getContext('2d')}const rect=document.getElementById('map').getBoundingClientRect(),scale=devicePixelRatio||1,canvas=amedasRain.canvas;canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale);const ctx=amedasRain.ctx;ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.globalAlpha=.62;const half=Math.max(2,Math.min(16,Math.pow(2,map.getZoom()-5)*2.6));amedasRain.values.forEach((value,i)=>{if(value<.1)return;const point=map.latLngToContainerPoint([analysis.points[i*2],analysis.points[i*2+1]]);ctx.fillStyle=value>=100?'#3f007d':value>=50?'#7a0177':value>=20?'#d7301f':value>=10?'#fc8d59':value>=5?'#41b6c4':'#a1dab4';ctx.fillRect(point.x-half,point.y-half,half*2+.6,half*2+.6)});ctx.globalAlpha=1}
function drawAnalysis(){if(!analysis.points||!analysis.values)return;ensureCanvas();const canvas=analysis.canvas,rect=document.getElementById('map').getBoundingClientRect(),scale=devicePixelRatio||1;canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;if(canvas.width!==Math.round(rect.width*scale)||canvas.height!==Math.round(rect.height*scale)){canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale)}const ctx=analysis.ctx;ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.globalAlpha=analysis.opacity;const zoom=map.getZoom(),half=Math.max(2,Math.min(16,Math.pow(2,zoom-5)*2.6));for(let i=0;i<analysis.values.length;i++){const lat=analysis.points[i*2],lon=analysis.points[i*2+1];if(!map.getBounds().pad(.03).contains([lat,lon]))continue;const p=map.latLngToContainerPoint([lat,lon]);ctx.fillStyle=analysisColor(analysis.values[i]);ctx.fillRect(p.x-half,p.y-half,half*2+.6,half*2+.6)}ctx.globalAlpha=1}
function activeSlots(){return analysis.kind==='medaka'?analysis.manifest.medaka.slots:analysis.manifest.slots}
function renderTimeline(){const slots=activeSlots();analysis.slot=Math.min(analysis.slot,slots.length-1);document.getElementById('timeline').innerHTML=`<button data-tl-step="-1">‹</button><input id="timelineRange" type="range" min="0" max="${slots.length-1}" value="${analysis.slot}" aria-label="対象時刻"><button data-tl-step="1">›</button><div class="timeline-jumps">${slots.map((slot,i)=>`<button data-slot-index="${i}">${slot.label}</button>`).join('')}</div>`;document.querySelectorAll('[data-slot-index]').forEach(button=>button.addEventListener('click',()=>loadSlot(Number(button.dataset.slotIndex))));document.getElementById('timelineRange').addEventListener('input',event=>loadSlot(Number(event.target.value)));document.querySelectorAll('[data-tl-step]').forEach(button=>button.addEventListener('click',()=>loadSlot(Math.max(0,Math.min(activeSlots().length-1,analysis.slot+Number(button.dataset.tlStep))))))}
function setLegend(){const values=analysis.kind==='moisture'?['うるおい残量','100 十分','50','0 乾燥','標準条件・雨だけを考慮']:analysis.kind==='watering'?['水やりナビ','根腐れ注意','水やり不要','水やり候補','判定ラベル6種']:analysis.kind==='rootrot'?['根腐れ注意MAP','根腐れ注意','湿りが続く','心配なし','wetStress由来の4段階']:['メダカあふれリスク','非常に高','中','低','標準60L・余裕3cm'];['legendTitle','legendHigh','legendMid','legendLow','legendNote'].forEach((id,i)=>document.getElementById(id).textContent=values[i]);document.getElementById('legendBar').style.background=analysis.kind==='moisture'?'linear-gradient(#1f5fa8,#4a90d9,#a8d08d,#e8c547,#b5651d)':analysis.kind==='watering'?'linear-gradient(#a23b3b,#8e77ad,#8d6e63,#2d87c8,#5e9f68,#d95f02)':analysis.kind==='rootrot'?'linear-gradient(#a23b3b,#8e77ad,#d1b36f,#5e9f68)':'linear-gradient(#c62828,#ed7d31,#f2c84b,#74add1)'}
function enhanceLegend(){const legend=document.querySelector('.legend'),note=document.getElementById('legendNote');legend.classList.toggle('discrete',analysis.kind!=='moisture');if(analysis.kind==='watering')note.innerHTML=['水やり候補','水やり不要','雨で回復','水やり見送り','湿り気味','根腐れ注意'].map((x,i)=>`<span style="--chip:${LABEL_COLORS[i]}">${x}</span>`).join('');else if(analysis.kind==='rootrot')note.innerHTML=['心配なし','湿り気味','湿りが続いている','根腐れ注意'].map((x,i)=>`<span style="--chip:${['#5e9f68','#d1b36f','#8e77ad','#a23b3b'][i]}">${x}</span>`).join('');else if(analysis.kind==='medaka')note.innerHTML=['低','中','高','非常に高'].map((x,i)=>`<span style="--chip:${MEDAKA_COLORS[i]}">${x}</span>`).join('')}
function conditionOffset(){const value=id=>document.getElementById(id).value,maps={mapPlant:{moist_lover:6,foliage:0,dry:-10},mapSize:{small:-6,standard:0,large:6},mapDrying:{moist:10,standard:0,dry:-10},mapRain:{full:0,eaves:-7,inside:-14},mapSun:{sun:0,half:4,shade:8,dark:12},mapSpeed:{slow:7,standard:0,fast:-7}};return Object.entries(maps).reduce((sum,[id,table])=>sum+(table[value(id)]??0),0)}
async function calculateMedakaRisk(slot){const n=analysis.manifest.grid_count,rain=await buffer(analysis.manifest.hourly.rain,Float32Array),times=analysis.manifest.hourly.times,ci=analysis.manifest.current_index||0,target=Math.max(ci,times.findIndex(value=>value===slot.validtime_jst)),container=document.getElementById('medakaContainer').value,area=container==='60'?.315:container==='40'?.24:.12,cover=Number(document.getElementById('medakaCover').value),drain=Number(document.getElementById('medakaOverflow').value),allowance=Number(document.getElementById('medakaAllowance').value),fry=document.getElementById('medakaFry').checked,stored=new Float32Array(n);for(let h=ci+1;h<=target;h++){const offset=h*n;for(let i=0;i<n;i++)stored[i]=Math.max(0,stored[i]+rain[offset+i]*area*cover-drain)}return Uint8Array.from(stored,value=>{const ratio=value/(area*10*allowance)*(fry?1.2:1);return ratio>1?3:ratio>=.9?2:ratio>=.5?1:0})}
function updateInfoBar(){const slot=activeSlots()?.[analysis.slot],layer=document.getElementById('analysisLayer').selectedOptions[0]?.textContent||'',mode=analysis.kind==='medaka'?'メダカ容器':document.getElementById('modeSelect').selectedOptions[0]?.textContent||'',source=amedasRain.enabled?`｜観測: ${document.getElementById('observedLayer').selectedOptions[0].textContent}`:'';document.getElementById('mapInfoBar').textContent=`${layer}｜${mode}｜${slot?.label||'--'}${slot?.validtime_jst?`＝${new Date(slot.validtime_jst).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'numeric'})}`:''}${source}`}
async function loadSlot(index){analysis.slot=index;const slot=activeSlots()[index];if(analysis.kind==='medaka'){analysis.values=await calculateMedakaRisk(slot)}else{const ref=slot.layers[analysis.mode],response=await fetch(`./data/${ref.file}`),raw=new Uint8Array(await response.arrayBuffer()),offset=conditionOffset(),adjusted=Uint8Array.from(raw,value=>Math.max(0,Math.min(100,value+offset)));if(analysis.kind==='moisture')analysis.values=adjusted;else{const labelResponse=await fetch(`./data/${ref.label_file}`),labels=new Uint8Array(await labelResponse.arrayBuffer());analysis.values=analysis.kind==='rootrot'?Uint8Array.from(labels,(code,i)=>code===5?3:code===4?1:adjusted[i]>=88?2:0):labels}}document.querySelectorAll('[data-slot-index]').forEach((button,i)=>button.classList.toggle('active',i===index));const range=document.getElementById('timelineRange');if(range)range.value=index;document.getElementById('mapStampText').textContent=`${slot.label}｜${slot.status==='partial'?'提供時間内の集計':'気象庁予報を使った計算'}`;setLegend();enhanceLegend();document.getElementById('mapStampText').dataset.valueCounts=JSON.stringify(analysis.values.reduce((a,v)=>(a[v]=(a[v]||0)+1,a),{}));updateInfoBar();drawAnalysis()}
async function initAnalysis(){const [manifestResponse,pointsResponse,prefResponse]=await Promise.all([fetch('./data/moisture_manifest.json'),fetch('./data/static/grid_points.bin'),fetch('./data/static/grid_pref_names.json')]);analysis.manifest=await manifestResponse.json();analysis.points=new Float32Array(await pointsResponse.arrayBuffer());analysis.prefNames=await prefResponse.json();renderTimeline();await loadSlot(0);applySharedState();renderTimeline();await loadSlot(analysis.slot)}
document.getElementById('modeSelect').addEventListener('change',event=>{analysis.mode=event.target.value;loadSlot(analysis.slot)});document.getElementById('opacityRange').addEventListener('input',event=>{analysis.opacity=Number(event.target.value)/100;drawAnalysis()});map.on('move zoom resize',drawAnalysis);
map.on('move zoom resize',drawAmedasRain);
async function loadObservedLayer(kind){amedasRain.kind=kind;amedasRain.enabled=Boolean(kind)&&kind!=='weather';if(kind==='weather'){setStatus('推計天気分布は次段階で接続します');amedasRain.enabled=false}if(amedasRain.enabled){const rain=await buffer(analysis.manifest.hourly.rain,Float32Array),n=analysis.manifest.grid_count,ci=analysis.manifest.current_index||0,hours=kind==='rain72h'?72:kind==='rain48h'?48:kind==='rain24h'?24:1,start=Math.max(0,ci-hours+1),values=new Float32Array(n);for(let h=start;h<=ci;h++){const o=h*n;for(let i=0;i<n;i++)values[i]+=rain[o+i]}amedasRain.values=values;setStatus(`${document.getElementById('observedLayer').selectedOptions[0].textContent}を表示中`)}if(amedasRain.canvas)amedasRain.canvas.hidden=!amedasRain.enabled;drawAmedasRain();updateInfoBar()}
document.getElementById('observedLayer').addEventListener('change',event=>loadObservedLayer(event.target.value));
if(document.getElementById('amedasToggle'))document.getElementById('amedasToggle').addEventListener('change',async event=>loadObservedLayer(event.target.checked?'rain1h':''));
document.getElementById('analysisLayer').addEventListener('change',event=>{analysis.kind=event.target.value;analysis.slot=0;document.getElementById('plantModeLabel').hidden=analysis.kind==='medaka';document.getElementById('medakaConditions').hidden=analysis.kind!=='medaka';document.getElementById('conditionNote').hidden=analysis.kind==='medaka';renderTimeline();loadSlot(0).then(()=>{if(analysis.selectedGrid!==null)selectGrid(analysis.selectedGrid,{showPanel:!document.getElementById('floatingDetail').hidden})})});
['mapPlant','mapSize','mapDrying','mapRain','mapSun','mapSpeed','mapWet'].forEach(id=>document.getElementById(id).addEventListener('change',()=>loadSlot(analysis.slot)));
['medakaContainer','medakaAllowance','medakaCover','medakaOverflow','medakaFry'].forEach(id=>document.getElementById(id).addEventListener('change',()=>loadSlot(analysis.slot).then(()=>{if(analysis.selectedGrid!==null)selectGrid(analysis.selectedGrid,{showPanel:!document.getElementById('floatingDetail').hidden})})));
document.addEventListener('keydown',event=>{if(event.target.matches('input,select,textarea')||!['ArrowLeft','ArrowRight'].includes(event.key)||!analysis.manifest)return;const next=Math.max(0,Math.min(activeSlots().length-1,analysis.slot+(event.key==='ArrowRight'?1:-1)));if(next!==analysis.slot){event.preventDefault();loadSlot(next)}});
map.on('mousemove',event=>{if(!showTooltip||!analysis.points||!analysis.values)return;let best=-1,dist=Infinity;for(let i=0;i<analysis.values.length;i++){const dy=analysis.points[i*2]-event.latlng.lat,dx=(analysis.points[i*2+1]-event.latlng.lng)*Math.cos(event.latlng.lat*Math.PI/180),d=dx*dx+dy*dy;if(d<dist){dist=d;best=i}}const tooltip=document.getElementById('tooltip');if(best<0||dist>.02){tooltip.hidden=true;return}const p=map.latLngToContainerPoint(event.latlng);tooltip.hidden=false;tooltip.style.left=`${p.x+14}px`;tooltip.style.top=`${p.y+14}px`;const value=analysis.values[best],rain=amedasRain.values?amedasRain.values[best]:null,rainText=rain!==null?`｜雨量 ${rain.toFixed(1)}mm`:'';tooltip.textContent=analysis.kind==='moisture'?`格子 ${best}｜うるおい残量 ${value}%${rainText}`:analysis.kind==='watering'?`格子 ${best}｜判定 ${labelText(value)}${rainText}`:analysis.kind==='rootrot'?`格子 ${best}｜${rootrotText(value)}${rainText}`:`格子 ${best}｜あふれリスク ${['低','中','高','非常に高'][value]}${rainText}`});map.on('mouseout',()=>document.getElementById('tooltip').hidden=true);
initAnalysis().catch(error=>{setStatus(`解析データを読み込めません: ${error.message}`);console.error(error)});

function nearestGrid(latlng){let best=-1,dist=Infinity;for(let i=0;i<analysis.values.length;i++){const dy=analysis.points[i*2]-latlng.lat,dx=(analysis.points[i*2+1]-latlng.lng)*Math.cos(latlng.lat*Math.PI/180),d=dx*dx+dy*dy;if(d<dist){dist=d;best=i}}return best}
function labelText(code){return ['水やり候補','水やり不要','雨で回復','水やり見送り','湿り気味','根腐れ注意'][code]||'水やり不要'}
function rootrotText(code){return ['心配なし','湿り気味','湿りが続いている','根腐れ注意'][code]||'心配なし'}
async function buffer(path,Type){if(!analysis.hourly[path]){const response=await fetch(`./data/${path}`);analysis.hourly[path]=new Type(await response.arrayBuffer())}return analysis.hourly[path]}
async function selectGrid(gridId){analysis.selectedGrid=gridId;document.getElementById('itemGrid').value=`格子 ${gridId}`;const n=analysis.manifest.grid_count,rain=await buffer(analysis.manifest.hourly.rain,Float32Array),count=analysis.manifest.hourly.times.length,rainValues=[];for(let h=0;h<count;h++)rainValues.push(rain[h*n+gridId]);document.getElementById('detailGrid').textContent=`格子 ${gridId}`;if(analysis.kind==='medaka'){const level=await buffer(analysis.manifest.hourly.medaka.level_cm,Float32Array),risk=await buffer(analysis.manifest.hourly.medaka.risk,Uint8Array),values=[];for(let h=0;h<count;h++)values.push(level[h*n+gridId]);const overflow=values.findIndex(v=>v>analysis.manifest.medaka.assumptions.allowance_cm),riskText=['低','中','高','非常に高'][risk[(analysis.manifest.current_index||0)*n+gridId]];document.getElementById('detailMoisture').textContent=`+${values[analysis.manifest.current_index||0].toFixed(1)}cm`;document.getElementById('detailLabel').textContent=`あふれリスク ${riskText}`;document.getElementById('detailReason').textContent=overflow>=0?`${new Date(analysis.manifest.hourly.times[overflow]).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'numeric'})}頃に満水ラインを超える計算です。排水口と雨よけを確認してください。`:'提供期間内は満水ライン未満の計算です。';drawMedakaChart(values,rainValues,analysis.manifest.medaka.assumptions.allowance_cm);return}const mode=analysis.mode,files=analysis.manifest.hourly.files[mode],[moisture,codes]=await Promise.all([buffer(files.moisture,Uint8Array),buffer(files.labels,Uint8Array)]),values=[],labelValues=[];for(let h=0;h<count;h++){values.push(moisture[h*n+gridId]);labelValues.push(codes[h*n+gridId])}const currentIndex=analysis.manifest.current_index||0,current=values[currentIndex],label=labelText(labelValues[currentIndex]);document.getElementById('detailMoisture').textContent=`${current}%`;document.getElementById('detailLabel').textContent=label;document.getElementById('detailReason').textContent=label==='水やり候補'?'乾きが進んでいます。実物の土や鉢の重さも確認してください。':label==='根腐れ注意'?'湿り気味の状態が続く計算です。排水と風通しを確認してください。':'今後の雨と乾き方を確認しながら管理してください。';drawDetailChart(values,rainValues);await renderCalendar(gridId)}
function drawDetailChart(values,rain){const canvas=document.getElementById('detailChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pad=42,times=analysis.manifest.hourly.times,boundary=analysis.manifest.forecast_start_index||0,line=analysis.mode==='farm'?35:analysis.mode==='ground'?20:30,x=i=>pad+i*(w-pad*2)/(values.length-1);ctx.clearRect(0,0,w,h);ctx.fillStyle='#e8f1f8';ctx.fillRect(x(boundary),pad,w-pad-x(boundary),h-pad*2);ctx.strokeStyle='#d5dfdc';ctx.lineWidth=1;ctx.font='12px sans-serif';ctx.fillStyle='#60716d';for(let v=0;v<=100;v+=25){const y=h-pad-v*(h-pad*2)/100;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke();ctx.fillText(`${v}%`,4,y+4)}const lineY=h-pad-line*(h-pad*2)/100;ctx.strokeStyle='#d95f02';ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(pad,lineY);ctx.lineTo(w-pad,lineY);ctx.stroke();ctx.setLineDash([]);ctx.fillText(`水やりライン ${line}%`,pad+4,lineY-5);ctx.strokeStyle='#23735f';ctx.lineWidth=4;ctx.beginPath();values.forEach((v,i)=>{const y=h-pad-v*(h-pad*2)/100;i?ctx.lineTo(x(i),y):ctx.moveTo(x(i),y)});ctx.stroke();ctx.fillStyle='#4a90d9aa';rain.forEach((v,i)=>ctx.fillRect(x(i)-3,h-pad-Math.min(50,v)*2,6,Math.min(50,v)*2));ctx.fillStyle='#17352f';for(let i=0;i<times.length;i+=12)ctx.fillText(new Date(times[i]).toLocaleString('ja-JP',{day:'numeric',hour:'numeric'}),x(i)-16,h-8);ctx.fillText('うるおい残量（線）／雨量（棒）',pad,22)}
function drawMedakaChart(values,rain,line){const canvas=document.getElementById('detailChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pad=42,max=Math.max(line*1.25,...values,1);ctx.clearRect(0,0,w,h);ctx.fillStyle='#e8f1f8';ctx.fillRect(w*.18,pad,w*.82,h-pad*2);const yLine=h-pad-line*(h-pad*2)/max;ctx.strokeStyle='#c62828';ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(pad,yLine);ctx.lineTo(w-pad,yLine);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#c62828';ctx.fillText(`満水ライン ${line}cm`,pad,yLine-6);ctx.strokeStyle='#23735f';ctx.lineWidth=4;ctx.beginPath();values.forEach((v,i)=>{const x=pad+i*(w-pad*2)/(values.length-1),y=h-pad-v*(h-pad*2)/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#17352f';ctx.fillText('累積水位上昇（線）／満水ライン（赤）',pad,22)}
async function renderCalendar(gridId){document.getElementById('calendarTitle').textContent='管理カレンダー｜格子 '+gridId+'・'+(analysis.prefNames?.[gridId]||'地域不明');if(!analysis.daily){const response=await fetch(`./data/${analysis.manifest.daily}`);analysis.daily=await response.json()}const mode=analysis.mode;document.getElementById('calendarDays').innerHTML=analysis.daily.days.map(day=>{const item=day.modes[mode],min=item.min[gridId],max=item.max[gridId],label=labelText(item.label[gridId]),klass=label==='水やり候補'?'caution':label==='雨で回復'?'recovery':label==='水やり見送り'?'defer':label.includes('湿')||label.includes('根腐れ')?'wet':'';return `<article class="calendar-card ${klass}"><b>${day.date}</b><strong>${label}</strong><span>${min}〜${max}%</span><small>${label==='水やり候補'?'乾き具合を確認':'雨と乾き方を確認'}</small>${day.trend?'<span class="trend">傾向</span>':''}</article>`}).join('')}
function syncFloating(showPanel=true){const panel=document.getElementById('floatingDetail'),source=document.getElementById('detailChart'),target=document.getElementById('floatingChart');document.getElementById('floatingGrid').textContent=document.getElementById('detailGrid').textContent+'・'+(analysis.prefNames?.[analysis.selectedGrid]||'');document.getElementById('floatingValue').textContent=document.getElementById('detailMoisture').textContent;document.getElementById('floatingLabel').textContent=document.getElementById('detailLabel').textContent;document.getElementById('floatingReason').textContent=document.getElementById('detailReason').textContent;const ctx=target.getContext('2d');ctx.clearRect(0,0,target.width,target.height);ctx.drawImage(source,0,0,target.width,target.height);if(showPanel)panel.hidden=false}
const floatingPanel=document.getElementById('floatingDetail');L.DomEvent.disableClickPropagation(floatingPanel);L.DomEvent.disableScrollPropagation(floatingPanel);document.getElementById('floatingClose').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();document.getElementById('floatingDetail').hidden=true});let floatingDrag=null;document.getElementById('floatingHandle').addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;const panel=document.getElementById('floatingDetail'),rect=panel.getBoundingClientRect();floatingDrag={dx:event.clientX-rect.left,dy:event.clientY-rect.top};event.currentTarget.setPointerCapture(event.pointerId)});document.getElementById('floatingHandle').addEventListener('pointermove',event=>{if(!floatingDrag)return;const panel=document.getElementById('floatingDetail'),host=document.querySelector('.map-panel').getBoundingClientRect();panel.style.left=Math.max(0,event.clientX-host.left-floatingDrag.dx)+'px';panel.style.top=Math.max(0,event.clientY-host.top-floatingDrag.dy)+'px';panel.style.bottom='auto'});document.getElementById('floatingHandle').addEventListener('pointerup',()=>floatingDrag=null);
function openDetailModal(){document.getElementById('detailModal').hidden=false}
function closeDetailModal(){document.getElementById('detailModal').hidden=true}
document.getElementById('openDetailModal').addEventListener('click',openDetailModal);
document.getElementById('detailModalClose').addEventListener('click',closeDetailModal);
document.getElementById('detailModal').addEventListener('click',event=>{if(event.target.id==='detailModal')closeDetailModal()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDetailModal()});
let legendDrag=null;document.getElementById('legendBox').addEventListener('pointerdown',event=>{const box=document.getElementById('legendBox'),rect=box.getBoundingClientRect(),host=document.querySelector('.map-panel').getBoundingClientRect();legendDrag={dx:event.clientX-rect.left,dy:event.clientY-rect.top};box.classList.add('dragging');box.style.left=`${rect.left-host.left}px`;box.style.top=`${rect.top-host.top}px`;box.style.right='auto';box.style.bottom='auto';box.setPointerCapture(event.pointerId)});document.getElementById('legendBox').addEventListener('pointermove',event=>{if(!legendDrag)return;const box=document.getElementById('legendBox'),host=document.querySelector('.map-panel').getBoundingClientRect();box.style.left=Math.max(6,Math.min(host.width-120,event.clientX-host.left-legendDrag.dx))+'px';box.style.top=Math.max(6,Math.min(host.height-120,event.clientY-host.top-legendDrag.dy))+'px'});document.getElementById('legendBox').addEventListener('pointerup',event=>{legendDrag=null;event.currentTarget.classList.remove('dragging')});
const selectGridBase=selectGrid;
selectGrid=async function(gridId,options={}){const showPanel=options.showPanel??true;await selectGridBase(gridId);if(analysis.kind==='medaka'){syncFloating(showPanel);return}const files=analysis.manifest.hourly.files[analysis.mode],moisture=await buffer(files.moisture,Uint8Array),n=analysis.manifest.grid_count,line=analysis.mode==='farm'?35:analysis.mode==='ground'?20:30,count=analysis.manifest.hourly.times.length,currentIndex=analysis.manifest.current_index||0;let arrival=-1;for(let h=currentIndex;h<count;h++){if(moisture[h*n+gridId]<=line){arrival=h;break}}const suffix=arrival===currentIndex?'現在、水やりライン以下です。':arrival>currentIndex?`${new Date(analysis.manifest.hourly.times[arrival]).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'numeric'})}頃に水やりラインへ到達する計算です。`:'提供期間内は水やりライン未到達です。';document.getElementById('detailReason').textContent+=suffix;syncFloating(showPanel)}
map.on('click',event=>{if(!analysis.values)return;const id=nearestGrid(event.latlng);if(id>=0)selectGrid(id,{showPanel:true})});
document.getElementById('modeSelect').addEventListener('change',()=>{if(analysis.selectedGrid!==null)selectGrid(analysis.selectedGrid,{showPanel:!document.getElementById('floatingDetail').hidden})});
document.getElementById('openMydata').addEventListener('click',()=>document.getElementById('mydataView').hidden=false);
document.getElementById('closeMydata').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();document.getElementById('mydataView').hidden=true});

const DB_NAME='water_care',DB_VERSION=1,STORE='items';let dbPromise;
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return dbPromise}
async function getItems(){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function putItem(item){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).put(item);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function deleteItem(id){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function wateringTime(item){if(!analysis.manifest||item.mode==='medaka')return '--';const files=analysis.manifest.hourly.files[item.mode],moisture=await buffer(files.moisture,Uint8Array),n=analysis.manifest.grid_count,count=analysis.manifest.hourly.times.length,line=item.mode==='farm'?35:item.mode==='ground'?20:30,current=moisture[item.grid_id],boost=item.logs.some(log=>log.type==='water_full')?Math.max(0,95-current):item.logs.some(log=>log.type==='water_light')?40:0;for(let h=0;h<count;h++){if(Math.min(100,moisture[h*n+item.grid_id]+boost)<=line)return new Date(analysis.manifest.hourly.times[h]).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'numeric'})}return '提供期間内は未到達'}
async function itemStatus(item){if(!analysis.manifest)return '読込中';if(item.mode==='medaka')return 'メダカ容器';const refs=analysis.manifest.hourly.files[item.mode],n=analysis.manifest.grid_count,i=(analysis.manifest.current_index||0)*n+item.grid_id,[moisture,labels]=await Promise.all([buffer(refs.moisture,Uint8Array),buffer(refs.labels,Uint8Array)]);return `${moisture[i]}%・${labelText(labels[i])}`}
async function renderItems(){const items=await getItems(),container=document.getElementById('itemList');if(!items.length){container.innerHTML='<p>まだ登録がありません。</p>';return}const rows=[];for(const item of items){const medaka=item.mode==='medaka',actions=medaka?`<button class="water" data-log-id="${item.id}" data-log-type="water_change">水換え</button><button data-log-id="${item.id}" data-log-type="top_up">足し水</button><button data-log-id="${item.id}" data-log-type="rain_cover">雨よけ</button>`:`<button class="water" data-log-id="${item.id}" data-log-type="water_full">たっぷり水やり</button><button data-log-id="${item.id}" data-log-type="water_light">軽く水やり</button><button data-log-id="${item.id}" data-log-type="rain_cover">雨よけ</button>`;rows.push(`<article class="item-row"><div><strong>${escapeText(item.name)}</strong><span>${escapeText(item.mode)}｜格子 ${item.grid_id}｜${await itemStatus(item)}｜${medaka?'雨対策':'水やり目安'} ${await wateringTime(item)}</span></div>${actions}<button data-delete-id="${item.id}">削除</button></article>`)}container.innerHTML=rows.join('');container.querySelectorAll('[data-log-id]').forEach(button=>button.addEventListener('click',()=>recordWater(button.dataset.logId,button.dataset.logType)));container.querySelectorAll('[data-delete-id]').forEach(button=>button.addEventListener('click',async()=>{await deleteItem(button.dataset.deleteId);renderItems()}))}
function escapeText(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function recordWater(id,type){const items=await getItems(),item=items.find(row=>row.id===id);if(!item)return;item.logs.push({ts:new Date().toISOString(),type,note:''});item.updated_at=new Date().toISOString();await putItem(item);renderItems()}
document.getElementById('itemForm').addEventListener('submit',async event=>{event.preventDefault();if(analysis.selectedGrid===null){setStatus('先に全国MAPで格子を選択してください');return}const items=await getItems();if(items.length>=20){setStatus('登録上限は20件です');return}const now=new Date().toISOString(),item={id:crypto.randomUUID(),name:document.getElementById('itemName').value.trim(),mode:document.getElementById('itemMode').value,location:{grid_id:analysis.selectedGrid,label:`格子 ${analysis.selectedGrid}`},grid_id:analysis.selectedGrid,preset_id:document.getElementById('itemPreset').value,simple_adjust:{dryness:document.getElementById('itemDryness').value,rain_exposure:document.getElementById('itemRain').value,sun:'full',wet_weakness:'normal',watering_stance:'std',wind:'std'},advanced_overrides:{},logs:[],observations:[],correction:{dry_speed_factor:1,rain_eff_factor:1},reserved_dry_stress:null,created_at:now,updated_at:now};await putItem(item);event.target.reset();document.getElementById('itemGrid').value=`格子 ${analysis.selectedGrid}`;renderItems()});
document.getElementById('exportItems').addEventListener('click',async()=>{const payload={schema_version:1,notice:'location情報（約5km格子ID）が含まれます。生の緯度経度は含みません。',items:await getItems()};const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));link.download='water_care-mydata.json';link.click();URL.revokeObjectURL(link.href)});
document.getElementById('importItems').addEventListener('change',async event=>{const data=JSON.parse(await event.target.files[0].text());if(data.schema_version!==1||!Array.isArray(data.items))throw new Error('対応していないJSONです');for(const item of data.items.slice(0,20)){if(!Number.isInteger(item.grid_id)||item.location?.lat!==undefined||item.location?.lon!==undefined)throw new Error('位置情報契約に違反するJSONです');await putItem(item)}renderItems()});
renderItems().catch(error=>console.error(error));

function applySharedState(){const params=new URLSearchParams(location.search),mode=params.get('mode'),kind=params.get('layer'),slot=params.has('slot')?Number(params.get('slot')):null,grid=params.has('grid')?Number(params.get('grid')):null,opacity=params.has('op')?Number(params.get('op')):null,base=params.get('base'),conditionIds=['mapPlant','mapSize','mapDrying','mapRain','mapSun','mapSpeed','mapWet'],conditions=(params.get('c')||'').split(',');const compat={flower:'foliage',cover:'inside',west:'sun',very_dry:'dry',very_fast:'fast'};conditionIds.forEach((id,i)=>{const value=compat[conditions[i]]||conditions[i];if(value&&[...document.getElementById(id).options].some(option=>option.value===value))document.getElementById(id).value=value});if(['pot_outdoor','ground','farm'].includes(mode)){analysis.mode=mode;document.getElementById('modeSelect').value=mode}if(['moisture','watering','rootrot','medaka'].includes(kind)){analysis.kind=kind;document.getElementById('analysisLayer').value=kind;document.getElementById('plantModeLabel').hidden=kind==='medaka';document.getElementById('medakaConditions').hidden=kind!=='medaka';document.getElementById('conditionNote').hidden=kind==='medaka'}if(Number.isInteger(slot)&&slot>=0&&slot<activeSlots().length)analysis.slot=slot;if(Number.isInteger(grid)&&grid>=0&&grid<31296){analysis.selectedGrid=grid;selectGrid(grid,{showPanel:false});const lat=analysis.points?.[grid*2],lon=analysis.points?.[grid*2+1];if(Number.isFinite(lat)&&Number.isFinite(lon))map.setView([lat,lon],Math.max(6,Number(params.get('z'))||6))}if(opacity!==null&&Number.isFinite(opacity)&&opacity>=0&&opacity<=100){analysis.opacity=opacity/100;document.getElementById('opacityRange').value=opacity}if(TILE[base])setBase(base);setTab(params.get('tab')||'map')}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok}}
document.getElementById('copyLink').addEventListener('click',async()=>{const url=new URL("https://nature-wx-lab.github.io/water_care/");url.search='';url.searchParams.set('layer',analysis.kind);url.searchParams.set('mode',analysis.mode);url.searchParams.set('slot',analysis.slot);url.searchParams.set('base',activeBase);url.searchParams.set('op',Math.round(analysis.opacity*100));url.searchParams.set('z',map.getZoom());url.searchParams.set('c',['mapPlant','mapSize','mapDrying','mapRain','mapSun','mapSpeed','mapWet'].map(id=>document.getElementById(id).value).join(','));if(analysis.selectedGrid!==null)url.searchParams.set('grid',analysis.selectedGrid);const button=document.getElementById('copyLink');button.dataset.lastUrl=url.toString();const ok=await copyText(url.toString());button.textContent=ok?'コピー済み':'コピー失敗';setTimeout(()=>button.textContent='リンクコピー',1200)});
function drawExportLegend(ctx,width){const title=document.getElementById('legendTitle').textContent,labels=[document.getElementById('legendHigh').textContent,document.getElementById('legendMid').textContent,document.getElementById('legendLow').textContent],colors=analysis.kind==='moisture'?['#1f5fa8','#a8d08d','#b5651d']:analysis.kind==='watering'?['#a23b3b','#2d87c8','#d95f02']:['#c62828','#f2c84b','#74add1'];ctx.fillStyle='#fffffff0';ctx.fillRect(width-155,58,143,112);ctx.fillStyle='#17352f';ctx.font='bold 12px sans-serif';ctx.fillText(title,width-145,76);ctx.font='10px sans-serif';labels.forEach((label,i)=>{ctx.fillStyle=colors[i];ctx.fillRect(width-145,87+i*24,18,14);ctx.fillStyle='#17352f';ctx.fillText(label,width-120,98+i*24)})}
document.getElementById('saveImage').addEventListener('click',async()=>{const button=document.getElementById('saveImage');try{const mapElement=document.getElementById('map'),rect=mapElement.getBoundingClientRect(),scale=2,out=document.createElement('canvas');out.width=Math.round(rect.width*scale);out.height=Math.round(rect.height*scale);const ctx=out.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#fff';ctx.fillRect(0,0,rect.width,rect.height);const images=[...mapElement.querySelectorAll('.leaflet-tile-loaded')];await Promise.all(images.map(image=>image.decode?.().catch(()=>{})));for(const image of images){const r=image.getBoundingClientRect();try{ctx.drawImage(image,r.left-rect.left,r.top-rect.top,r.width,r.height)}catch{}}if(analysis.canvas)ctx.drawImage(analysis.canvas,0,0,rect.width,rect.height);drawExportLegend(ctx,rect.width);ctx.fillStyle='#fffffff0';ctx.fillRect(10,rect.height-58,360,48);ctx.fillStyle='#17352f';ctx.font='bold 14px sans-serif';ctx.fillText('Nature Wx Lab｜うるおい管理ナビ',18,rect.height-38);ctx.font='11px sans-serif';const slot=activeSlots()[analysis.slot];ctx.fillText(`${slot.label}｜格子 ${analysis.selectedGrid??'未選択'}｜出典: 気象庁データを加工`,18,rect.height-20);const link=document.createElement('a');link.href=out.toDataURL('image/png');link.download=`water_care-map-${slot.id}.png`;button.dataset.imageReady=`${out.width}x${out.height}`;button.dataset.imageLegend=document.getElementById('legendTitle').textContent;delete button.dataset.imageError;link.click();button.textContent='保存済み'}catch(error){button.dataset.imageError=error.name;button.textContent='保存失敗';console.error(error)}setTimeout(()=>button.textContent='画像保存',1200)});
